DEBUG = False

PRINT_FAILED_TESTS = True # Set to true to print failed tests, if false then an AssertionError is raised instead.
USE_LAGRANGE_INVERSION_FOR_HUREWICZ_IMAGE_OF_PROJECTIVE_SPACES = True
DISPLAY_DOLD_MANIFOLD_INDICES_MANIFOLD_BASIS = False
SEE_CHANGE_OF_BASIS_MATRIX_STATUS_FOR_E_TO_W_BASIS = False
SEE_CHANGE_OF_BASIS_MATRIX_STATUS_FOR_E_TO_W_BASIS_TELL_AFTER_EACH_ROW = False